setlocal
cd /d %~dp0
javac -sourcepath .\src .\src\controller\GameEngine.java
javac -sourcepath .\src .\src\controller\GameState.java
javac -sourcepath .\src .\src\controller\KeyBindings.java
javac -sourcepath .\src .\src\controller\MapManager.java
javac -sourcepath .\src .\src\controller\MouseController.java
javac -sourcepath .\src .\src\controller\action\ClickButton.java
javac -sourcepath .\src .\src\controller\action\Move.java
javac -sourcepath .\src .\src\controller\action\SelectProjectile.java
javac -sourcepath .\src .\src\controller\action\SelectWeapon.java
javac -sourcepath .\src .\src\controller\action\SetAttack.java
javac -sourcepath .\src .\src\controller\action\SetState.java
javac -sourcepath .\src .\src\controller\action\StopMove.java
javac -sourcepath .\src .\src\model\Animation.java
javac -sourcepath .\src .\src\model\Camera.java
javac -sourcepath .\src .\src\model\Character.java
javac -sourcepath .\src .\src\model\Enemy.java
javac -sourcepath .\src .\src\model\GameConstants.java
javac -sourcepath .\src .\src\model\ImageLoader.java
javac -sourcepath .\src .\src\model\Inventory.java
javac -sourcepath .\src .\src\model\Map.java
javac -sourcepath .\src .\src\model\Movement.java
javac -sourcepath .\src .\src\model\Player.java
javac -sourcepath .\src .\src\model\Portal.java
javac -sourcepath .\src .\src\model\ShooterEnemy.java
javac -sourcepath .\src .\src\model\Sprite.java
javac -sourcepath .\src .\src\model\Team.java
javac -sourcepath .\src .\src\model\Tile.java
javac -sourcepath .\src .\src\model\TileObject.java
javac -sourcepath .\src .\src\model\VisualEffect.java
javac -sourcepath .\src .\src\model\Wall.java
javac -sourcepath .\src .\src\model\item\HpItem.java
javac -sourcepath .\src .\src\model\item\Item.java
javac -sourcepath .\src .\src\model\item\ItemType.java
javac -sourcepath .\src .\src\model\item\ProjectileItem.java
javac -sourcepath .\src .\src\model\item\WeaponItem.java
javac -sourcepath .\src .\src\model\weapon\Bow.java
javac -sourcepath .\src .\src\model\weapon\Gun.java
javac -sourcepath .\src .\src\model\weapon\Melee.java
javac -sourcepath .\src .\src\model\weapon\NoWeapon.java
javac -sourcepath .\src .\src\model\weapon\Projectile.java
javac -sourcepath .\src .\src\model\weapon\ProjectileStat.java
javac -sourcepath .\src .\src\model\weapon\ProjectileType.java
javac -sourcepath .\src .\src\model\weapon\Shooter.java
javac -sourcepath .\src .\src\model\weapon\Spear.java
javac -sourcepath .\src .\src\model\weapon\Sword.java
javac -sourcepath .\src .\src\model\weapon\Weapon.java
javac -sourcepath .\src .\src\model\weapon\WeaponClass.java
javac -sourcepath .\src .\src\model\weapon\WeaponFactory.java
javac -sourcepath .\src .\src\model\weapon\WeaponID.java
javac -sourcepath .\src .\src\model\weapon\WeaponStat.java
javac -sourcepath .\src .\src\model\weapon\WeaponType.java
javac -sourcepath .\src .\src\view\ConstraintBuilder.java
javac -sourcepath .\src .\src\view\GameFrame.java
javac -sourcepath .\src .\src\view\GameScreen.java
javac -sourcepath .\src .\src\view\HealthBar.java
javac -sourcepath .\src .\src\view\HomeScreen.java
javac -sourcepath .\src .\src\view\InventoryItem.java
javac -sourcepath .\src .\src\view\InventoryUI.java
javac -sourcepath .\src .\src\view\PauseScreen.java
javac -sourcepath .\src .\src\view\ProjectileList.java
javac -sourcepath .\src .\src\view\UIManager.java
javac -sourcepath .\src .\src\view\WeaponList.java
javac -sourcepath .\src .\src\welp\poc\Main.java
pause
java -classpath .\src welp.poc.Main